language: python
python:
  - "3.6"
# command to install dependencies
install:
    - pip install numpy
    - pip install scipy
    - pip install requests
# command to run tests
script: python adrsm -d ./data/genomes -t 1 ./data/short_genome_list.csv
