{% set version = "0.9.5" %}

package:
  name: adrsm
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/maxibor/adrsm.git

requirements:
  build:
    - python 3.6.*
    - setuptools
  run:
    - python >=3.6.*
    - numpy  >=1.18.1
    - scipy  >=1.3.1
    - requests >=2.22
    - click
    - xopen


test:
  commands:
    - adrsm --help

about:
  home: https://github.com/maxibor/adrsm
  license: MIT
  summary: 'Ancient DNA Read Simulator for Metagenomics'
